spring:
  application:
    name: GateWay
  cloud:
    loadbalancer:
      ribbon:
        enabled: true
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: GBFRouter
#          uri: http://localhost:8090
          uri: lb://GBF
          predicates:
            - Path=/GBF/**
          filters:
            - StripPrefix=1
        - id: TOKEN
#          uri: http://localhost:8087
          uri: lb://TOKEN
          predicates:
            - Path=/TOKEN/**
          filters:
            - StripPrefix=1

eureka:
  instance:
    #显示IP地址
    prefer-ip-address: true
    #默认值为：机器名称：服务名称：实例得端口
    instance-id: ${spring.application.name}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://root:123456@localhost:8081/eureka/eureka
    register-with-eureka: true
    fetch-registry: true
server:
  port: 8888
